services:
  # ────────────────────────── ERP API ──────────────────────────
  erp-api:
    build:
      context: ../apps/erp-api
      target: development
    volumes:
      - ../apps/erp-api:/app
    ports:
      - '4000:4000'

  # ────────────────── Accounting service (hot-reload) ──────────
  accounting-svc:
    build:
      context: ../apps/accounting-svc
      target: development
    volumes:
      - ../apps/accounting-svc:/app
    ports:
      - '4100:4100'

  # ─────────────────── React + Vite front-end ──────────────────
  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
      target: development
    volumes:
      - ../apps/web:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: http://erp-api:4000
    ports:
      - '5174:5173'
