########################
#  Shared infrastructure
########################
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ['27017:27017']
    volumes: ['mongo-data:/data/db']

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounting_dev
    ports: ['5432:5432']
    volumes: ['pg-data:/var/lib/postgresql/data']

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # Management UI

  ########################
  #  Application services
  ########################
  erp-api:
    build:
      context: ../apps/erp-api
      target: production
    env_file: ../apps/erp-api/.env
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - '4000:4000'

  accounting-svc:
    build:
      context: ../apps/accounting-svc
      target: production
    env_file: ../apps/accounting-svc/.env
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - '4100:4100'

  web:
    build:
      context: ../apps/web
      target: production
    depends_on:
      - erp-api
    ports:
      - '5173:80'
########################
#  Volumes
########################
volumes:
  mongo-data:
  pg-data:
  cms-uploads:
