name: ERP‑API CI

on:
  pull_request:
    branches:
      - dev
      - master
    paths:
      - 'apps/erp-api/**'
      - '.github/workflows/apps-erp-api-ci.yml'
      - 'compose/**'
      - 'package.json'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  # Job to get changed files and determine what to test
  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.get-changed-files.outputs.all_changed_files }}
      has-erp-api-changes: ${{ steps.get-changed-files.outputs.has_erp_api_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: get-changed-files
        run: |
          # Get the base commit based on target branch
          if [ "${{ github.base_ref }}" = "master" ]; then
            BASE_COMMIT=$(git rev-parse origin/master)
          else
            BASE_COMMIT=$(git rev-parse origin/dev)
          fi
          
          # Get changed files between PR and target branch
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Filter for ERP API related files ONLY (not compose or other files)
          ERP_API_FILES=$(echo "$CHANGED_FILES" | grep -E "^apps/erp-api/" || true)
          
          # Check if there are actual ERP API changes
          if [ -n "$ERP_API_FILES" ]; then
            echo "has_erp_api_changes=true" >> $GITHUB_OUTPUT
            echo "ERP API changed files:"
            echo "$ERP_API_FILES"
          else
            echo "has_erp_api_changes=false" >> $GITHUB_OUTPUT
            echo "No ERP API application changes detected"
          fi
          
          echo "all_changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  # Main ERP API testing and validation job (for dev branch)
  erp-api-ci-dev:
    name: ERP‑API Tests & Build (Dev)
    runs-on: ubuntu-latest
    needs: get-changed-files
    if: needs.get-changed-files.outputs.has-erp-api-changes == 'true' && github.base_ref == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn workspace erp-api install --frozen-lockfile

      - name: Get changed test files
        id: get-test-files
        run: |
          BASE_COMMIT=$(git rev-parse origin/dev)
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT HEAD)
          
          # Filter for test files in ERP API
          TEST_FILES=$(echo "$CHANGED_FILES" | grep -E "apps/erp-api/.*\.(test|spec)\.(js|ts)$" || true)
          
          # Filter for source files that have corresponding tests
          SOURCE_FILES=$(echo "$CHANGED_FILES" | grep -E "apps/erp-api/src/.*\.(js|ts)$" | grep -v "\.(test|spec)\.(js|ts)$" || true)
          
          # Find corresponding test files for changed source files
          CORRESPONDING_TESTS=""
          for file in $SOURCE_FILES; do
            # Convert source file path to test file path
            TEST_FILE=$(echo "$file" | sed 's/\.js$/.test.js/' | sed 's/\.ts$/.test.ts/' | sed 's/src\//src\/__tests__\//')
            if [ -f "$TEST_FILE" ]; then
              CORRESPONDING_TESTS="$CORRESPONDING_TESTS $TEST_FILE"
            fi
          done
          
          # Combine all test files
          ALL_TEST_FILES="$TEST_FILES $CORRESPONDING_TESTS"
          
          if [ -n "$ALL_TEST_FILES" ]; then
            echo "test_files<<EOF" >> $GITHUB_OUTPUT
            echo "$ALL_TEST_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "has_tests=true" >> $GITHUB_OUTPUT
            echo "Running tests for files: $ALL_TEST_FILES"
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
            echo "No test files found for changed files"
          fi

      - name: Run ESLint
        run: yarn workspace erp-api lint

      - name: Run Jest tests on changed files
        id: run-tests
        if: steps.get-test-files.outputs.has_tests == 'true'
        run: |
          TEST_FILES="${{ steps.get-test-files.outputs.test_files }}"
          echo "Running tests for: $TEST_FILES"
          
          # Run tests for specific files
          yarn workspace erp-api test --ci $TEST_FILES
          
          # Check if tests passed
          if [ $? -eq 0 ]; then
            echo "test_status=passed" >> $GITHUB_OUTPUT
          else
            echo "test_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Run all tests if no specific test files
        id: run-all-tests
        if: steps.get-test-files.outputs.has_tests == 'false'
        run: |
          echo "No specific test files found, running all tests"
          yarn workspace erp-api test --ci
          
          if [ $? -eq 0 ]; then
            echo "test_status=passed" >> $GITHUB_OUTPUT
          else
            echo "test_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Build Docker image
        id: build-docker
        if: steps.run-tests.outputs.test_status == 'passed' || steps.run-all-tests.outputs.test_status == 'passed'
        run: |
          echo "Building Docker image..."
          docker build -t erp-api:ci apps/erp-api
          
          if [ $? -eq 0 ]; then
            echo "docker_status=passed" >> $GITHUB_OUTPUT
          else
            echo "docker_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Test Docker Compose
        id: test-compose
        if: steps.build-docker.outputs.docker_status == 'passed'
        run: |
          echo "Testing Docker Compose..."
          
          # Start services in background
          docker-compose -f compose/compose.base.yml -f compose/compose.dev.yml up -d mongo postgres rabbitmq
          
          # Wait for services to be ready
          sleep 10
          
          # Test ERP API service
          docker-compose -f compose/compose.base.yml -f compose/compose.dev.yml run --rm erp-api echo "ERP API service test passed"
          
          if [ $? -eq 0 ]; then
            echo "compose_status=passed" >> $GITHUB_OUTPUT
          else
            echo "compose_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          # Cleanup
          docker-compose -f compose/compose.base.yml -f compose/compose.dev.yml down

      - name: Auto-merge PR
        id: auto-merge
        if: steps.test-compose.outputs.compose_status == 'passed'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'squash'
              });
              console.log('PR auto-merged successfully');
              return 'merged';
            } catch (error) {
              console.log('Auto-merge failed:', error.message);
              return 'failed';
            }

      - name: Create failure issue
        if: failure()
        run: |
          echo "Creating failure issue for ERP API CI..."
          echo "PR: ${{ github.event.pull_request.number }}"
          echo "Branch: ${{ github.head_ref }} → ${{ github.base_ref }}"
          echo "Commit: ${{ github.sha }}"
        continue-on-error: true

  # Docker Compose only job (for master branch)
  erp-api-compose-master:
    name: ERP API Docker Compose (Master)
    runs-on: ubuntu-latest
    needs: get-changed-files
    if: needs.get-changed-files.outputs.has-erp-api-changes == 'true' && github.base_ref == 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Docker Compose
        id: test-compose
        run: |
          echo "Testing Docker Compose for master branch..."
          
          # Start services in background
          docker-compose -f compose/compose.base.yml -f compose/compose.dev.yml up -d mongo postgres rabbitmq
          
          # Wait for services to be ready
          sleep 10
          
          # Test ERP API service
          docker-compose -f compose/compose.base.yml -f compose/compose.dev.yml run --rm erp-api echo "ERP API service test passed"
          
          if [ $? -eq 0 ]; then
            echo "compose_status=passed" >> $GITHUB_OUTPUT
          else
            echo "compose_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          # Cleanup
          docker-compose -f compose/compose.base.yml -f compose/compose.dev.yml down

      - name: Auto-merge PR
        id: auto-merge
        if: steps.test-compose.outputs.compose_status == 'passed'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'squash'
              });
              console.log('PR auto-merged successfully');
              return 'merged';
            } catch (error) {
              console.log('Auto-merge failed:', error.message);
              return 'failed';
            }

      - name: Create failure issue
        if: failure()
        run: |
          echo "Creating failure issue for ERP API Docker Compose..."
          echo "PR: ${{ github.event.pull_request.number }}"
          echo "Branch: ${{ github.head_ref }} → ${{ github.base_ref }}"
          echo "Commit: ${{ github.sha }}"
        continue-on-error: true

  # Job to handle PRs with no ERP API changes
  no-changes:
    name: No ERP API Changes
    runs-on: ubuntu-latest
    needs: get-changed-files
    if: needs.get-changed-files.outputs.has-erp-api-changes == 'false'
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '✅ No ERP API changes detected in this PR. CI checks skipped.'
              });
              console.log('Comment added successfully');
            } catch (error) {
              console.log('Could not add comment to PR:', error.message);
              // Continue without failing the workflow
            }
