name: ERP‑API CI

on:
  pull_request:
    branches:
      - dev
      - master
    paths:
      - 'apps/erp-api/**'
      - '.github/workflows/apps-erp-api-ci.yml'
      - 'compose/**'
      - 'package.json'

# Use minimal permissions by default, grant specific permissions only when needed
permissions:
  contents: read
  pull-requests: read
  issues: read

jobs:
  # Job to get changed files and determine what to test
  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.get-changed-files.outputs.all_changed_files }}
      has-erp-api-changes: ${{ steps.get-changed-files.outputs.has_erp_api_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: get-changed-files
        run: |
          # Get the base commit based on target branch
          if [ "${{ github.base_ref }}" = "master" ]; then
            BASE_COMMIT=$(git rev-parse origin/master)
          else
            BASE_COMMIT=$(git rev-parse origin/dev)
          fi
          
          # Get changed files between PR and target branch
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Filter for ERP API related files ONLY (not compose or other files)
          ERP_API_FILES=$(echo "$CHANGED_FILES" | grep -E "^apps/erp-api/" || true)
          
          # Check if there are actual ERP API changes
          if [ -n "$ERP_API_FILES" ]; then
            echo "has_erp_api_changes=true" >> $GITHUB_OUTPUT
            echo "ERP API changed files:"
            echo "$ERP_API_FILES"
          else
            echo "has_erp_api_changes=false" >> $GITHUB_OUTPUT
            echo "No ERP API application changes detected"
          fi
          
          echo "all_changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  # PR to dev: Test → Build Dockerfile
  erp-api-dev-pipeline:
    name: ERP‑API Dev Pipeline (Test → Build)
    runs-on: ubuntu-latest
    needs: get-changed-files
    if: needs.get-changed-files.outputs.has-erp-api-changes == 'true' && github.base_ref == 'dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn workspace erp-api install --frozen-lockfile

      - name: Run linting
        run: |
          cd apps/erp-api
          yarn lint

      - name: Run tests
        run: |
          cd apps/erp-api
          yarn test

      - name: Build Docker image
        run: |
          cd apps/erp-api
          docker build -t erp-api:test .

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ ERP API Dev Pipeline: Tests passed and Docker image built successfully!'
            })

  # PR to master: Docker Compose
  erp-api-master-pipeline:
    name: ERP‑API Master Pipeline (Docker Compose)
    runs-on: ubuntu-latest
    needs: get-changed-files
    if: needs.get-changed-files.outputs.has-erp-api-changes == 'true' && github.base_ref == 'master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Docker Compose
        id: test-compose
        run: |
          echo "Testing Docker Compose for master branch..."
          
          # Start services in background
          docker compose -f compose/compose.base.yml -f compose/compose.dev.yml up -d mongo postgres rabbitmq
          
          # Wait for services to be ready
          sleep 10
          
          # Test ERP API service
          docker compose -f compose/compose.base.yml -f compose/compose.dev.yml run --rm erp-api echo "ERP API service test passed"
          
          if [ $? -eq 0 ]; then
            echo "compose_status=passed" >> $GITHUB_OUTPUT
          else
            echo "compose_status=failed" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          # Cleanup
          docker compose -f compose/compose.base.yml -f compose/compose.dev.yml down

      - name: Auto-merge PR
        id: auto-merge
        if: steps.test-compose.outputs.compose_status == 'passed'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                merge_method: 'squash'
              });
              console.log('PR auto-merged successfully');
              return 'merged';
            } catch (error) {
              console.log('Auto-merge failed:', error.message);
              return 'failed';
            }

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ ERP API Master Pipeline: Docker Compose test passed! PR will be auto-merged.'
            })

  # Job to handle PRs with no ERP API changes
  no-changes:
    name: No ERP API Changes
    runs-on: ubuntu-latest
    needs: get-changed-files
    if: needs.get-changed-files.outputs.has-erp-api-changes == 'false'
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⏭️ No ERP API changes detected. Skipping ERP API CI pipeline.'
            })
