name: CI – ERP API Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev-apps-erp-api

jobs:
  erp-api-test:
    name: Run ERP-API Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: apps/erp-api
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        working-directory: apps/erp-api
        run: yarn test
